### ISSUE TITLE
Animate image load

### ISSUE THREAD

**Issue by designbyadrian** [mbrevda/react-image#143]
Hello, is it possible to have images fade in when loaded? I'd be happy with just a CSS-class being added when image is finished loading, or just an event firing when done.

**Comment by mbrevda** [comment]
All props are [passed through](https://github.com/mbrevda/react-image/blob/master/src/index.js#L137) to the underlying `<img>`, so you have pretty much full control over the rendering of the final `<img>` element. Perhaps this needs to be clarified in the docs.

**Comment by designbyadrian** [comment]
Hello, thank you for replying. What props should I pass down, though? I'm not receiving any events from `Img`, so I don't know when the image is done loading.

**Comment by mbrevda** [comment]
Any props passed to `<Img>` which aren't used by image itself will be padded to the underlying `<img>`. So if you do  
```js
<Img src="foo" onLoad={() => console.log('Image loaded!')}>
```
it should log when the image was loaded

**Comment by designbyadrian** [comment]
Oh, I didn't get you could hijack those props! Thanks!

**Comment by mbrevda** [comment]
Let me know if that works!

**Comment by AntonioRedondo** [comment]
This is not possible with the [current implementation](https://github.com/mbrevda/react-image/blob/master/src/index.js#L145). Even when the prop `onLoad` can be passed down to the `<img>` element the prop `loader` is removed/not rendered if the image is loaded. That is to say, only one of the two can be rendered at the same time. This prevents creating transitions between loader and image.

**Comment by mbrevda** [comment]
> This prevents creating transitions between loader and image.

What would be needed in order to animate between the loader and the final
image?

**Comment by AntonioRedondo** [comment]
Both the loader and the `<img>` would need to be rendered, and with CSS or inline-styling they would be positioned absolute. Something like [this](https://medium.com/jsguru/react-image-lazy-loading-component-246e0cdcce02). However the code to implement this shouldn't be as complex as the one of the link.

**Comment by AntonioRedondo** [comment]
Since the `onLoad` event can be passed to the `<img>` element the end-user developer could wrap your component into a sandwich of `<div>`s and change the opacity when `onLoad` is executed. However this defeats the purpose of having a 3rd-party component. With the current implementation the difference we get is that now the image will load at once rather than progressively in vertical. But no chance of applying transitions. It would be nice if this functionality was implemented on the component.

**Comment by mbrevda** [comment]
I wonder if accepting a function that can be rendered instead of I'm would
allow for more flexibility here?

**Comment by AntonioRedondo** [comment]
Yeah, that sounds well, as long as this function is called with the state of the image and it's allowed being rendered after the image is loaded.

**Comment by AntonioRedondo** [comment]
Another easy way to implement transitions would be using `::before` or `::after` pseudo-elements which would fade away after `onLoad` is called. This actually wouldn't require code changes. I'll try to experiment with this tomorrow.

**Comment by mbrevda** [comment]
This should be a pretty simple change. Would you send a PR?

**Comment by AntonioRedondo** [comment]
Yep, no prob. Let's see tomorrow whether I get it working and hopefully I could have something to commit.

**Comment by mbrevda** [comment]
Great, thanks. Let me know if you need help.

**Comment by mbrevda** [comment]
Were you able to make any progress with this? I was experimenting and this is what I came up with:

![trans](https://user-images.githubusercontent.com/293004/36430696-8181803c-165e-11e8-866a-eccb27ece42d.gif)

**Comment by AntonioRedondo** [comment]
Hi @mbrevda. Sorry for not coming back to this. Busy times. I came across with a similar visual solution to yours using the `onLoad` attribute. But I did it at work without time to move results to an isolated component and project.

Your solution looks great! When I was working on my implementation I came across with a small issue. After first time the image loads this is cached. So that means that on successive times the animation transition will be shown at moment 0. It would be ideal if there is some way to check whether the image is on the cache, and on this case avoiding the transition since the image will load straight away. Not a big issue anyway.

Another challenge is the initial dimensions of the pictures, which are unknown. I see you're giving some defaults.

I feel curious about how are you implementing this. If you want, once you have a pull request I can review it and see how you have done it.

**Comment by mbrevda** [comment]
I don't believe it is possible to check if a file is in the cache. You can see my current implementation (and planned changes) in 23c28848fbf2938d42e238a8f140f9b833dbdcab. 

> Another challenge is the initial dimensions of the pictures, which are unknown. I see you're giving some defaults.

Where are you talking about?

**Comment by AntonioRedondo** [comment]
I just had a look to the changes. It's a good idea to use this `react-css-transition-replace` with automatic height animation.

There is small issue with the current changes. The preloader height doesn't adjust to the image height once this is loaded during the transition. Check the below gif (I set the preloader background in red and slowed down the transition for a better visualisation):
![before](https://media.giphy.com/media/XJ1YthnxbWEGy0CaGR/giphy.gif)

I've created a [pull request](https://github.com/mbrevda/react-image/pull/189) which addresses this. After the changes the transitions is like below:
![after](https://media.giphy.com/media/28c6v8uFCvfDsLGMcm/giphy.gif)

Are you wrapping and offering `TransitionDemo` component as an importable component or just leaving it as a recipe? I think the first would be an easier way of using your package as it would be ready to use. You'd just have to include new props for `transitionName`, `transitionEnterTimeout` and `transitionLeaveTimeout`.

**Comment by mbrevda** [comment]
Thanks! The goal of this project isn't to provide a transition framework or specialized transition components. It would seem that the adding a wrapper function gives the user enough flexibility to implement transitions and other advanced rendering options whilst still keeping this component clean and simple.
