### ISSUE TITLE
Release version 1.3.2?

### ISSUE THREAD

**Issue by juhah** [mbrevda/react-image#203]
Could you do a new release to `npm`, the last release is from 9 months ago. We use your lib in our app and there have been fixes since the last release that we'd like to include (especially #194). Thanks!

**Comment by mbrevda** [comment]
Yes, if course. On the todo list for today!

On Aug 3, 2018 1:39 PM, "juhah" <notifications@github.com> wrote:

Could you do a new release to npm, the last release is from 9 months ago.
We use your lib in our app and there have been fixes since the last release
that we'd like to include (especially #194
<https://github.com/mbrevda/react-image/pull/194>). Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mbrevda/react-image/issues/203>, or mute the thread
