### ISSUE TITLE
SSR an <img>

### ISSUE THREAD

**Issue by mxstbr** [mbrevda/react-image#206]
Right now when server-side rendering `react-image` will render the loading indicator, as verified by these tests: e263bf3

That's not very ideal behavior though. If a user has JavaScript disabled, or the JS bundle fails to load for whatever reason, they'll only ever see the loading indicator, never the actual image.

Why shouldn't we SSR `<img src={props.src} />` so the image can load even if JS is disabled, and then swap it out with the loader if the JS rehydrates and the image hasn't loaded yet?

**Comment by mbrevda** [comment]
In lue of any real data, these are some of the assumptions that were made when designing the current behaviour:

1. Most users _are_ using JS
1. `react-image` will most often be used on pages with _multiple_ images
1. Loaders will most often be the _same component or image_ across the site (for visual consistency) 
1. Loaders will often be _packed_ in the js as either an svg or blob, eliminating the need for a server call just to load the loader (because if your making a server trip, just request the image!)
1. Images are important - _but not critical_ - for the user to see on page load

Hence the use case optimized for was js enabled with multiple images and a single loader; the goal being to get a loader on the screen asap, and then deal with loading the images later. In _this_ scenario, SSR'ing the loader seemed like the sensible thing to do. We don't want all the images loading as soon as the page loads (i.e. if all the images were ssr'd) as that would block loading other things on the page, and instead we'll wait a bit and do other work in the meantime. This also allows for some advanced use cases such as [delaying loading an image until the element is visible in the viewport](https://github.com/mbrevda/react-image#delay-rendering-until-element-is-visible-lazy-rendering).

Anyway, that was the original idea. I'd love to hear your challenges to these assumptions!

(as a nitpick, there is no way to know if the browser has already loaded the image afaik, and should we use `<img>` server side, we would be forced to either remove all images, flash a loader, and then flash back to the image, or just skip all the loaders on ssr'd images at the risk of an image not showing up and at the risk of disabling advanced use cases as above)

**Comment by mbrevda** [comment]
Closing due to a lack of feedback - would be happy to discuss further!
