### ISSUE TITLE
Images with CORS policy

### ISSUE THREAD

**Issue by petewalker** [mbrevda/react-image#227]
Occasionally, we need to load images from domains with a CORS policy. This means setting the `crossorigin` attribute on the `img` tag (and on an `Image` object when loading from JavaScript).

Currently `react-image` doesn't allow you to specify this on the `Image` used to load images, so it simply fails. Could we create a `crossorigin` prop on `Img`?

e.g.

```js
const myComponent = () => (
  <Img src={'https://www.example.com/foo.jpg'} crossorigin="anonymous" />
)
```

**Comment by mbrevda** [comment]
Reopening to track implementation in hooks branch

**Comment by jharris4** [comment]
Hi, I just started using https on a site built with `react-image` and I'm getting cors errors because the `Image.crossOrigin` is not being set properly.

I see that the code currently does:

```
const i = new Image();
if (this.props.crossorigin) {
  i.crossorigin = this.props.crossorigin;
}
```

The problem is that the `crossOrigin` property is **camelCase** in the [HTMLImageElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement), and you can also find [examples here](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image)
