### ISSUE TITLE
Allow a prop to add alt text

### ISSUE THREAD

**Issue by NPrada** [mbrevda/react-image#264]
All people to pass through a simple string as the alt text on the image element. 
This is better for web usability and SEO.
I am happy to make a pr to get this added

**Comment by mbrevda** [comment]
Any extra props passed to react-image will be passed to the final `<img>` element when it's loaded

**Comment by Tom-xacademy** [comment]
@mbrevda It may not be a problem for javascript but with typescript, it will fail to compile because the d.ts doesn't have definition for the alt. Additionally, I can't use 'className' or any other prop either.

This is from the 2.2.0 react-image version which allowed the addition of className and alt, though there was no typing for it.
```ts
export interface ImgProps {
      src?: string | string[]
      loader?: JSX.Element
      unloader?: JSX.Element
      decode?: boolean
      crossorigin?: string
      container?: () => JSX.Element
      loaderContainer?: () => JSX.Element
      unloaderContainer?: () => JSX.Element
  
      // For img element props such as 'alt'
      [key: string]: any
    }
```

In 2.4.0, you have this:
```ts
export interface ImgProps extends Omit<React.ComponentPropsWithoutRef<'img'>, 'src'> {
      src?: string | string[]
      loader?: JSX.Element
      unloader?: JSX.Element
      decode?: boolean
      crossorigin?: string
      container?: (children: React.ReactNode) => JSX.Element
      loaderContainer?: (children: React.ReactNode) => JSX.Element
      unloaderContainer?: (children: React.ReactNode) => JSX.Element
}
```
Image html elment types are described by: "React.ReactElement<React.ImgHTMLAttributes<HTMLImageElement>>".

Example:
```ts
const image: React.ReactElement<React.ImgHTMLAttributes<HTMLImageElement>> = <img src="/image.png" alt="some img alt" className="unique-classname" />
```

**Conclusion**: You should omit from the interface I posted above and or just simply extend it.

**Comment by mbrevda** [comment]
This should be addressed by https://github.com/mbrevda/react-image/pull/268
