### ISSUE TITLE
Nextjs SSG Dynamic routing didn't work after first route navigation

### ISSUE THREAD

**Issue by neamatmim** [mbrevda/react-image#337]
Hi,
when i use react-image within nextjs ssg with dynamic routing react-image didn't response as expected .
when i first click one of my post it's work fine but then i click another post from this page it'll always render loading state until any rerender .
please you can check it on https://codesandbox.io/s/github/neamatmim/nextjs-react-image.

Note: (previously It's work on 2.4.0, break on latest version)
Thanks for your great work

**Comment by mbrevda** [comment]
I don't use next.js, but looking at the network tab it doesn't seem to be returning valid data?
<img width="832" alt="Screen Shot 2020-10-04 at 3 40 23 PM" src="https://user-images.githubusercontent.com/293004/95015833-ecd16780-0657-11eb-82e7-619bc9acdb0a.png">

If you have a fix to propose, feel free to open a PR. Otherwise, not sure how else to be helpful here.
